key(keypad_1): 
    user.hitch2_s1()
key(keypad_2): 
    user.hitch2_s2()
key(keypad_3): 
    user.hitch2_s3()
key(keypad_4): 
    user.hitch2_s4()
key(keypad_5): 
    user.hitch2_s5()
key(keypad_6): 
    user.hitch2_s6()
key(keypad_7): 
    user.hitch2_s7()
key(keypad_8): 
    user.hitch2_s8()